<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Student;

class StudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {        $students = [
            [
                'student_id' => 'STU2025001',
                'first_name' => 'Alice',
                'last_name' => 'Anderson',
                'email' => 'alice.anderson@email.com',
                'phone' => '+1-555-0101',
                'date_of_birth' => '2000-03-15',
                'gender' => 'female',
                'address' => '123 Main St',
                'city' => 'Boston',
                'state' => 'MA',
                'country' => 'USA',
                'postal_code' => '02101',
                'emergency_contact' => 'Jane Anderson',
                'emergency_phone' => '+1-555-0102',
                'enrollment_date' => '2025-01-10',
                'status' => 'active',
            ],
            [
                'student_id' => 'STU2025002',
                'first_name' => 'Bob',
                'last_name' => 'Brown',
                'email' => 'bob.brown@email.com',
                'phone' => '+1-555-0201',
                'date_of_birth' => '1999-07-22',
                'gender' => 'male',
                'address' => '456 Oak Ave',
                'city' => 'Cambridge',
                'state' => 'MA',
                'country' => 'USA',
                'postal_code' => '02139',
                'emergency_contact' => 'Robert Brown Sr.',
                'emergency_phone' => '+1-555-0202',
                'enrollment_date' => '2025-01-12',
                'status' => 'active',
            ],
            [
                'student_id' => 'STU2025003',
                'first_name' => 'Carol',
                'last_name' => 'Davis',
                'email' => 'carol.davis@email.com',
                'phone' => '+1-555-0301',
                'date_of_birth' => '2001-11-08',
                'gender' => 'female',
                'address' => '789 Pine St',
                'city' => 'Palo Alto',
                'state' => 'CA',
                'country' => 'USA',
                'postal_code' => '94301',
                'emergency_contact' => 'Charles Davis',
                'emergency_phone' => '+1-555-0302',
                'enrollment_date' => '2025-01-14',
                'status' => 'active',
            ],
            [
                'student_id' => 'STU2025004',
                'first_name' => 'Daniel',
                'last_name' => 'Evans',
                'email' => 'daniel.evans@email.com',
                'phone' => '+1-555-0401',
                'date_of_birth' => '2000-09-30',
                'gender' => 'male',
                'address' => '321 Elm St',
                'city' => 'San Francisco',
                'state' => 'CA',
                'country' => 'USA',
                'postal_code' => '94105',
                'emergency_contact' => 'Diana Evans',
                'emergency_phone' => '+1-555-0402',
                'enrollment_date' => '2025-01-28',
                'status' => 'active',
            ],
            [
                'student_id' => 'STU2025005',
                'first_name' => 'Emma',
                'last_name' => 'Foster',
                'email' => 'emma.foster@email.com',
                'phone' => '+1-555-0501',
                'date_of_birth' => '1998-12-12',
                'gender' => 'female',
                'address' => '654 Maple Dr',
                'city' => 'Austin',
                'state' => 'TX',
                'country' => 'USA',
                'postal_code' => '78701',
                'emergency_contact' => 'Frank Foster',
                'emergency_phone' => '+1-555-0502',
                'enrollment_date' => '2025-02-10',
                'status' => 'active',
            ],
            [
                'student_id' => 'STU2025006',
                'first_name' => 'George',
                'last_name' => 'Garcia',
                'email' => 'george.garcia@email.com',
                'phone' => '+1-555-0601',
                'date_of_birth' => '2002-05-18',
                'gender' => 'male',
                'address' => '987 Cedar Ln',
                'city' => 'Houston',
                'state' => 'TX',
                'country' => 'USA',
                'postal_code' => '77001',
                'emergency_contact' => 'Grace Garcia',
                'emergency_phone' => '+1-555-0602',
                'enrollment_date' => '2025-01-15',
                'status' => 'active',
            ],
            [
                'student_id' => 'STU2025007',
                'first_name' => 'Hannah',
                'last_name' => 'Harris',
                'email' => 'hannah.harris@email.com',
                'phone' => '+1-555-0701',
                'date_of_birth' => '2001-01-25',
                'gender' => 'female',
                'address' => '147 Birch St',
                'city' => 'Seattle',
                'state' => 'WA',
                'country' => 'USA',
                'postal_code' => '98101',
                'emergency_contact' => 'Henry Harris',
                'emergency_phone' => '+1-555-0702',
                'enrollment_date' => '2025-01-30',
                'status' => 'active',
            ],
            [
                'student_id' => 'STU2025008',
                'first_name' => 'Ian',
                'last_name' => 'Jackson',
                'email' => 'ian.jackson@email.com',
                'phone' => '+1-555-0801',
                'date_of_birth' => '1999-10-14',
                'gender' => 'male',
                'address' => '258 Spruce Ave',
                'city' => 'Portland',
                'state' => 'OR',
                'country' => 'USA',
                'postal_code' => '97201',
                'emergency_contact' => 'Irene Jackson',
                'emergency_phone' => '+1-555-0802',
                'enrollment_date' => '2025-01-16',
                'status' => 'active',
            ],
            [
                'student_id' => 'STU2025009',
                'first_name' => 'Julia',
                'last_name' => 'King',
                'email' => 'julia.king@email.com',
                'phone' => '+1-555-0901',
                'date_of_birth' => '2000-08-07',
                'gender' => 'female',
                'address' => '369 Willow Way',
                'city' => 'Denver',
                'state' => 'CO',
                'country' => 'USA',
                'postal_code' => '80201',
                'emergency_contact' => 'Jack King',
                'emergency_phone' => '+1-555-0902',
                'enrollment_date' => '2025-01-18',
                'status' => 'active',
            ],
            [
                'student_id' => 'STU2025010',
                'first_name' => 'Kevin',
                'last_name' => 'Lee',
                'email' => 'kevin.lee@email.com',
                'phone' => '+1-555-1001',
                'date_of_birth' => '2001-06-03',
                'gender' => 'male',
                'address' => '741 Ash Blvd',
                'city' => 'Phoenix',
                'state' => 'AZ',
                'country' => 'USA',
                'postal_code' => '85001',
                'emergency_contact' => 'Karen Lee',
                'emergency_phone' => '+1-555-1002',
                'enrollment_date' => '2025-01-20',
                'status' => 'active',
            ]
        ];

        foreach ($students as $student) {
            Student::create($student);
        }
    }
}
